# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  port: 3306
  # socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  username: root
  password: root
  database: oms_development

production:
  <<: *default
  username: root
  password: root
  database: oms_production
